name: Lint and Check
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
on: push
jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Check
        run: npm run check
