base_url = "https://lhf.pt"

title = "Luís H. Fonseca"
description = "personal blog and portfolio"

author = "Luís H. Fonseca"

compile_sass = true
minify_html = true
generate_feed = true
#build_search_index = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "rose-pine"
extra_syntaxes_and_themes = [ './md_themes' ]
external_links_target_blank = true

[extra]
short_title = "lhf"
canonical = "https://lhf.pt"
