base_url = "https://lhf.pt"
title = "lhf."
description = "Personal website of Luís Fonseca"

compile_sass = true
#build_search_index = true
generate_feed = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "rose-pine"
extra_syntaxes_and_themes = [ './md_themes' ]
external_links_target_blank = true

[extra]
author = "Luís Fonseca"
